## code to prepare `CONFIG_SCHEMA` goes here
.CONFIG_SCHEMA <- readLines("./data-raw/gitlatex.schema.json")
.CONFIG_PRIVATE_SCHEMA <- readLines("./data-raw/gitlatex.private.schema.json")

## Core latex/pdflatex auxiliary files:
.LATEX_BUILD_FILES <- c(
  "*.aux",
  "*.lof",
  "*.log",
  "*.lot",
  "*.fls",
  "*.out",
  "*.toc",
  "*.fmt",
  "*.fot",
  "*.cb",
  "*.cb2",
  "*.dvi",
  "*.xdv",
  "*.bbl",
  "*.bcf",
  "*.blg",
  "*-blx.aux",
  "*-blx.bib",
  "*.run.xml",
  "*.fdb_latexmk",
  "*.synctex",
  "*.synctex(busy)",
  "*.synctex.gz",
  "*.synctex.gz(busy)",
  "*.pdfsync",
  "*.rubbercache",
  "*.alg",
  "*.loa",
  "*.thm",
  "*.nav",
  "*.pre",
  "*.snm",
  "*.vrb",
  "*.soc",
  "*.cut",
  "*.cpt",
  "*.spl",
  "*.ent",
  "*.lox",
  "*.mf",
  "*.mp",
  "*.tfm",
  "*.end",
  "*.?end",
  "*.acn",
  "*.acr",
  "*.glg",
  "*.glo",
  "*.gls",
  "*.glsdefs",
  "*.lzo",
  "*.lzs",
  "*.slg",
  "*.slo",
  "*.sls",
  "*.gnuplot",
  "*.table",
  "*.gaux",
  "*.glog",
  "*.gtex",
  "*.4ct",
  "*.4tc",
  "*.idv",
  "*.lg",
  "*.trc",
  "*.xref",
  "*.idx",
  "*.ilg",
  "*.ind",
  "*.maf",
  "*.mlf",
  "*.mlt",
  "*.hd",
  "*.brf",
  "*.lol",
  "*.ltjruby",
  "*.pyg",
  "*.mw",
  "*.newpax",
  "*.nlg",
  "*.nlo",
  "*.nls",
  "*.pax",
  "*.pdfpc",
  "*-concordance.tex",
  "*-tikzDictionary",
  "*.sagetex.sage",
  "*.sagetex.py",
  "*.sagetex.scmd",
  "*.wrt",
  "*.sout",
  "*.sympy",
  "*.upa",
  "*.upb",
  "*.pytxcode",
  "*.listing",
  "*.loe",
  "*.dpth",
  "*.md5",
  "*.auxlock",
  "*.ptc",
  "*.tdo",
  "*.hst",
  "*.ver",
  "*.lod",
  "*.xcp",
  "*.xmpi",
  "*.xdy",
  "*.xyc",
  "*.xyd",
  "*.ttt",
  "*.fff",
  "*.bak",
  "*.sav",
  "*.lyx~",
  "*.backup",
  "*.tps",
  "*.el",
  "*-tags.tex",
  "*.sta",
  "*.lpz",
  "*.xwm"
)
## turn .gitignore syntax into regex
.LATEX_BUILD_FILES <- gsub("*", "", .LATEX_BUILD_FILES, fixed = TRUE)
.LATEX_BUILD_FILES <- gsub(".", "\\.", .LATEX_BUILD_FILES, fixed = TRUE)
.LATEX_BUILD_FILES <- paste(.LATEX_BUILD_FILES, collapse = "|")
.LATEX_BUILD_FILES <- sprintf("^.*(%s)$", .LATEX_BUILD_FILES)

usethis::use_data(
  .CONFIG_SCHEMA, .CONFIG_PRIVATE_SCHEMA, .LATEX_BUILD_FILES,
  internal = TRUE, overwrite = TRUE
)
